/**
 * Second wave of primary-source B&R rows.
 * Dates and formats are the ones printed on those Wizards pages — no invented clocks.
 * Merged into volume-data.mjs.
 */

export const WAVE2_ANNOUNCEMENTS = [
  {
    id: '2019-01-21',
    title: 'January 21, 2019, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/january-21-2019-banned-and-restricted-announcement',
    author: 'Ian Duke',
    publishedAt: '2019-01-21',
    clocks: {tabletop: '2019-01-25', mtgo: '2019-01-21'},
    excerpt: `Modern: Krark-Clan Ironworks is banned.
Effective Date: January 25, 2019.
Magic Online Effective Date: January 21, 2019.`,
  },
  {
    id: '2019-10-21',
    title: 'October 21, 2019, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/october-21-2019-banned-and-restricted-announcement',
    author: 'Ian Duke',
    publishedAt: '2019-10-21',
    clocks: {tabletop: '2019-10-25', mtgo: '2019-10-21', arena: '2019-10-24'},
    excerpt: `Standard: Field of the Dead is banned.
Pauper: Arcum's Astrolabe is banned.
Tabletop Effective Date: Oct 25, 2019.
MTG Arena Effective Date: Oct 24, 2019.
Magic Online Effective Date: Oct 21, 2019.`,
  },
  {
    id: '2019-11-18',
    title: 'November 18, 2019, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/november-18-2019-banned-and-restricted-announcement',
    author: 'Ian Duke',
    publishedAt: '2019-11-18',
    clocks: {tabletop: '2019-11-22', mtgo: '2019-11-18', arena: '2019-11-18'},
    excerpt: `Standard: Oko, Thief of Crowns; Once Upon a Time; and Veil of Summer are banned.
Brawl: Oko, Thief of Crowns is banned.
Legacy: Wrenn and Six is banned.
Tabletop Effective Date: Nov 22, 2019.
MTG Arena Effective Date: Nov 18, 2019.
Magic Online Effective Date: Nov 18, 2019.`,
  },
  {
    id: '2019-12-16',
    title: 'December 16, 2019 Pioneer Banned Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/december-16-2019-pioneer-banned-announcement',
    author: 'Ian Duke',
    publishedAt: '2019-12-16',
    clocks: {tabletop: '2019-12-17', mtgo: '2019-12-17'},
    excerpt: `Pioneer: Oko, Thief of Crowns is banned. Nexus of Fate is banned.
Tabletop Effective Date: December 17, 2019.
Magic Online Effective Date: December 17, 2019.`,
  },
  {
    id: '2020-01-13',
    title: 'January 13, 2020, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/january-13-2020-banned-and-restricted-announcement',
    author: 'Wizards of the Coast',
    publishedAt: '2020-01-13',
    clocks: {tabletop: '2020-01-14', mtgo: '2020-01-14'},
    excerpt: `Modern: Mox Opal is banned. Oko, Thief of Crowns is banned. Mycosynth Lattice is banned.
Effective Date (Magic Online and tabletop): January 14, 2020.`,
  },
  {
    id: '2020-04-13',
    title: 'April 13, 2020, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/april-13-2020-banned-and-restricted-announcement',
    author: 'Ian Duke',
    publishedAt: '2020-04-13',
    clocks: {tabletop: '2020-04-16', mtgo: '2020-04-16', arena: '2020-04-16'},
    excerpt: `Brawl: Lutri, the Spellchaser is banned.
Tabletop Effective Date: April 16, 2020.
Magic Online Effective Date: April 16, 2020.
MTG Arena Effective Date: April 16, 2020.`,
  },
  {
    id: '2021-02-15',
    title: 'February 15, 2021, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/february-15-2021-banned-and-restricted-announcement',
    author: 'Ian Duke',
    publishedAt: '2021-02-15',
    clocks: {tabletop: '2021-02-15', mtgo: '2021-02-15', arena: '2021-02-15'},
    excerpt: `Historic: Omnath, Locus of Creation is banned (from suspended). Uro, Titan of Nature's Wrath is banned.
Pioneer: Balustrade Spy, Teferi, Time Raveler, Undercity Informer, Uro, and Wilderness Reclamation are banned.
Modern: Field of the Dead, Mystic Sanctuary, Simian Spirit Guide, Tibalt's Trickery, and Uro are banned.
Legacy: Arcum's Astrolabe, Dreadhorde Arcanist, and Oko are banned.
Vintage: Lurrus of the Dream-Den is unbanned.
Effective Date: February 15, 2021.`,
  },
  {
    id: '2021-06-09',
    title: 'June 9, 2021, Banned and Restricted Announcement',
    url: 'https://magic.wizards.com/en/news/announcements/june-9-2021-banned-and-restricted-announcement',
    author: 'Wizards of the Coast',
    publishedAt: '2021-06-09',
    clocks: {arena: '2021-06-10'},
    excerpt: `Historic: Time Warp is banned.
MTG Arena effective date: June 10, 2021.`,
  },
]

function row(partial) {
  return partial
}

export const WAVE2_ROWS = [
  row({
    subject: 'krark-clan-ironworks',
    name: 'Krark-Clan Ironworks',
    aliases: ['krark-clan ironworks', 'krark clan ironworks', 'ironworks'],
    predicate: 'legalInModern',
    announcement: '2019-01-21',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'field-of-the-dead',
    name: 'Field of the Dead',
    aliases: ['field of the dead'],
    predicate: 'legalInStandard',
    announcement: '2019-10-21',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'arcums-astrolabe',
    name: "Arcum's Astrolabe",
    aliases: ["arcum's astrolabe", 'arcums astrolabe', 'astrolabe'],
    predicate: 'legalInPauper',
    announcement: '2019-10-21',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'oko-thief-of-crowns',
    name: 'Oko, Thief of Crowns',
    aliases: ['oko, thief of crowns', 'oko'],
    predicate: 'legalInStandard',
    announcement: '2019-11-18',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'once-upon-a-time',
    name: 'Once Upon a Time',
    aliases: ['once upon a time'],
    predicate: 'legalInStandard',
    announcement: '2019-11-18',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'veil-of-summer',
    name: 'Veil of Summer',
    aliases: ['veil of summer'],
    predicate: 'legalInStandard',
    announcement: '2019-11-18',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'oko-thief-of-crowns',
    name: 'Oko, Thief of Crowns',
    aliases: ['oko, thief of crowns', 'oko'],
    predicate: 'legalInBrawl',
    announcement: '2019-11-18',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'wrenn-and-six',
    name: 'Wrenn and Six',
    aliases: ['wrenn and six', 'wrenn'],
    predicate: 'legalInLegacy',
    announcement: '2019-11-18',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'oko-thief-of-crowns',
    name: 'Oko, Thief of Crowns',
    aliases: ['oko, thief of crowns', 'oko'],
    predicate: 'legalInPioneer',
    announcement: '2019-12-16',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'nexus-of-fate',
    name: 'Nexus of Fate',
    aliases: ['nexus of fate', 'nexus'],
    predicate: 'legalInPioneer',
    announcement: '2019-12-16',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'mox-opal',
    name: 'Mox Opal',
    aliases: ['mox opal'],
    predicate: 'legalInModern',
    announcement: '2020-01-13',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'oko-thief-of-crowns',
    name: 'Oko, Thief of Crowns',
    aliases: ['oko, thief of crowns', 'oko'],
    predicate: 'legalInModern',
    announcement: '2020-01-13',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'mycosynth-lattice',
    name: 'Mycosynth Lattice',
    aliases: ['mycosynth lattice', 'mycosynth'],
    predicate: 'legalInModern',
    announcement: '2020-01-13',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'lutri-the-spellchaser',
    name: 'Lutri, the Spellchaser',
    aliases: ['lutri, the spellchaser', 'lutri'],
    predicate: 'legalInBrawl',
    announcement: '2020-04-13',
    action: 'banned',
    prior: 'legal',
  }),
  // Printed on the October 12, 2020 page; missed in the first seed.
  row({
    subject: 'lucky-clover',
    name: 'Lucky Clover',
    aliases: ['lucky clover'],
    predicate: 'legalInStandard',
    announcement: '2020-10-12',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'escape-to-the-wilds',
    name: 'Escape to the Wilds',
    aliases: ['escape to the wilds'],
    predicate: 'legalInStandard',
    announcement: '2020-10-12',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'teferi-time-raveler',
    name: 'Teferi, Time Raveler',
    aliases: ['teferi, time raveler', 'teferi'],
    predicate: 'legalInHistoric',
    announcement: '2020-10-12',
    action: 'banned',
    prior: 'suspended',
    priorFrom: {arena: '2020-08-03'},
  }),
  row({
    subject: 'wilderness-reclamation',
    name: 'Wilderness Reclamation',
    aliases: ['wilderness reclamation'],
    predicate: 'legalInHistoric',
    announcement: '2020-10-12',
    action: 'banned',
    prior: 'suspended',
    priorFrom: {arena: '2020-08-03'},
  }),
  row({
    subject: 'burning-tree-emissary',
    name: 'Burning-Tree Emissary',
    aliases: ['burning-tree emissary', 'burning tree emissary'],
    predicate: 'legalInHistoric',
    announcement: '2020-10-12',
    action: 'unbanned',
    prior: 'suspended',
    priorFrom: {arena: '2020-07-16'},
  }),
  row({
    subject: 'omnath-locus-of-creation',
    name: 'Omnath, Locus of Creation',
    aliases: ['omnath, locus of creation', 'omnath'],
    predicate: 'legalInHistoric',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'suspended',
    priorFrom: {arena: '2020-10-12'},
  }),
  row({
    subject: 'uro-titan-of-natures-wrath',
    name: "Uro, Titan of Nature's Wrath",
    aliases: ["uro, titan of nature's wrath", 'uro'],
    predicate: 'legalInHistoric',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'balustrade-spy',
    name: 'Balustrade Spy',
    aliases: ['balustrade spy'],
    predicate: 'legalInPioneer',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'teferi-time-raveler',
    name: 'Teferi, Time Raveler',
    aliases: ['teferi, time raveler', 'teferi'],
    predicate: 'legalInPioneer',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'undercity-informer',
    name: 'Undercity Informer',
    aliases: ['undercity informer'],
    predicate: 'legalInPioneer',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'uro-titan-of-natures-wrath',
    name: "Uro, Titan of Nature's Wrath",
    aliases: ["uro, titan of nature's wrath", 'uro'],
    predicate: 'legalInPioneer',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'wilderness-reclamation',
    name: 'Wilderness Reclamation',
    aliases: ['wilderness reclamation'],
    predicate: 'legalInPioneer',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'field-of-the-dead',
    name: 'Field of the Dead',
    aliases: ['field of the dead'],
    predicate: 'legalInModern',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'mystic-sanctuary',
    name: 'Mystic Sanctuary',
    aliases: ['mystic sanctuary'],
    predicate: 'legalInModern',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'simian-spirit-guide',
    name: 'Simian Spirit Guide',
    aliases: ['simian spirit guide', 'simian'],
    predicate: 'legalInModern',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'tibalts-trickery',
    name: "Tibalt's Trickery",
    aliases: ["tibalt's trickery", 'tibalts trickery', 'trickery'],
    predicate: 'legalInModern',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'uro-titan-of-natures-wrath',
    name: "Uro, Titan of Nature's Wrath",
    aliases: ["uro, titan of nature's wrath", 'uro'],
    predicate: 'legalInModern',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'arcums-astrolabe',
    name: "Arcum's Astrolabe",
    aliases: ["arcum's astrolabe", 'arcums astrolabe', 'astrolabe'],
    predicate: 'legalInLegacy',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'dreadhorde-arcanist',
    name: 'Dreadhorde Arcanist',
    aliases: ['dreadhorde arcanist', 'dreadhorde'],
    predicate: 'legalInLegacy',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'oko-thief-of-crowns',
    name: 'Oko, Thief of Crowns',
    aliases: ['oko, thief of crowns', 'oko'],
    predicate: 'legalInLegacy',
    announcement: '2021-02-15',
    action: 'banned',
    prior: 'legal',
  }),
  row({
    subject: 'lurrus-of-the-dream-den',
    name: 'Lurrus of the Dream-Den',
    aliases: ['lurrus of the dream-den', 'lurrus'],
    predicate: 'legalInVintage',
    announcement: '2021-02-15',
    action: 'unbanned',
    prior: 'banned',
    priorFrom: {tabletop: '2020-05-18', mtgo: '2020-05-18'},
  }),
  row({
    subject: 'time-warp',
    name: 'Time Warp',
    aliases: ['time warp'],
    predicate: 'legalInHistoric',
    announcement: '2021-06-09',
    action: 'banned',
    prior: 'legal',
  }),
]

export const WAVE2_WORKED = [
  {
    _id: 'call-field-arena-oct23',
    _type: 'workedCall',
    title: 'Field on Arena, October 23',
    question: 'On Arena, October 23 2019, is Field of the Dead banned in Standard?',
    date: '2019-10-23',
    finding: 'Not yet. Arena’s clock is October 24. Magic Online already banned it on October 21. Tabletop waits until October 25.',
  },
  {
    _id: 'call-oko-paper-nov20',
    _type: 'workedCall',
    title: 'Oko on paper, November 20',
    question: 'On paper, November 20 2019, is Oko banned in Standard?',
    date: '2019-11-20',
    finding: 'No. Tabletop’s clock is November 22. Arena and Magic Online banned Oko on November 18.',
  },
  {
    _id: 'call-ironworks-mtgo-jan21',
    _type: 'workedCall',
    title: 'Ironworks on Magic Online, January 21',
    question: 'On Magic Online, January 21 2019, is Krark-Clan Ironworks banned in Modern?',
    date: '2019-01-21',
    finding: 'Yes on Magic Online that day. Tabletop waits until January 25.',
  },
  {
    _id: 'call-lutri-arena-apr16',
    _type: 'workedCall',
    title: 'Lutri on Arena, April 16',
    question: 'On Arena, April 16 2020, is Lutri banned in Brawl?',
    date: '2020-04-16',
    finding: 'Yes. The April 13 page bans Lutri in Brawl on April 16 on every platform it names.',
  },
  {
    _id: 'call-time-warp-june9',
    _type: 'workedCall',
    title: 'Time Warp on Arena, June 9',
    question: 'On Arena, June 9 2021, is Time Warp banned in Historic?',
    date: '2021-06-09',
    finding: 'Not yet. The June 9 page’s Arena clock is June 10.',
  },
  {
    _id: 'call-lucky-clover-oct12',
    _type: 'workedCall',
    title: 'Lucky Clover, October 12',
    question: 'On Arena, October 12 2020, is Lucky Clover banned in Standard?',
    date: '2020-10-12',
    finding: 'Yes. The October 12 page bans Lucky Clover and Escape to the Wilds in Standard the same day as Omnath.',
  },
]
